README.md

https://bookkeeper.akuity.io is live now, so this PR updates links in the `README.md`.

update doc links in readme

---

.github/workflows/ci.yaml
.golangci.yaml
Dockerfile
Dockerfile.dev
Makefile
branches_test.go
cmd/cli/render_cmd.go
cmd/cli/version_cmd.go
cmd/main.go
config.go
config_test.go
context.go
go.mod
internal/git/git.go
internal/helm/helm.go
internal/kustomize/kustomize.go
service.go
service_test.go

This also includes a linter upgrade, which seems to have been necessary when stepping up to Go 1.20, adopts the same linter rules as Kargo, and addresses any linter issues discovered.
There are no functional changes in this PR.

upgrade to go 1.20.4

---

pkg/git/git.go

If we add these two functions to the `git` package, Kargo can re-use this package instead of duplicating it.

port two useful git commands from Kargo

---

service.go

This is a practical improvement discovered through our dogfooding.
Previous to this PR, the logic for building commit messages was this:
1. Let x represent the commit ID that the last env-specific render was based on (this comes from env/branch-specific metadata)
1. Let x' represent the commit ID you're now rendering from
1. Always use x' as the first line of the commit
1. If x != "", add all commit messages between x (last render source) and x' (current render source) into the new commit message
1. End the new commit message with a note that Bookkeeper generated this commit by rendering from x' (current render source)
_Step 4 turns out to be overkill_. When things are automated (and Bookkeeper is meant to be automated), step 4 never yields anything _unless_ there is a PR involved and …

reduce noise in repo history

---

action.yaml

Planning to cut another RC that will further reduce noise wherever we are dogfooding this. This PR updates the action definition in advance so that the action will reference the correct image.
Reminder that we'll figure out a way to automate this eventually: https://github.com/akuity/bookkeeper/issues/150

make bookkeeper action use upcoming release

---

docs/docs/30-how-to-guides/20-github-actions.md
docs/docs/30-how-to-guides/30-docker-image.md
rendering.go

Resolves https://github.com/akuity/bookkeeper/issues/156
Here's the fix for the problem we encountered while dogfooding.
There was a missing early-return when there was an issue with the pre-rendering process.
The result was that we continued with the next iteration of the loop, _didn't_ encounter an error, and the new `nil` error was clobbering the old non-`nil` error.

fix error-handling bug and update docs for a release

---

.github/governance.yml
.github/workflows/governance.yaml

Added the Governance bot similar to Kargo.
It still needs the Bookkeeper specific `area`'s defined, but that can be done with a follow-up PR.
closes #159

Added Governance bot closes #159

---

.github/governance.yml

This label seems to overlap entirely with kind/enhancement.

remove kind/feature label from governance bot

---

.github/workflows/ci.yaml
.golangci.yaml
Dockerfile.dev

This PR upgrades the golangci-linter and disables the depguard linter, which has breaking changes. It's usefulness is so small that it doesn't warrant fixing its configuration.

upgrade linter

---

action.yaml

The rc.19 action still references the buggy rc.18 image.
After this is merged, we'll cut an rc.20.
Note there is already an issue open to automate this process.

Update action definition to reference upcoming release

---

service.go

Fixes #166
This will prevent the nil pointer dereference that currently occurs when Bookkeeper is asked to write to an existing branch that isn't already Bookkeeper-managed.
It will return an error instead, which seems like the most sensible thing to do, because this was probably a mistake on the user's part.
If you _do_ want Bookkeeper to take over an existing branch, you can either delete the target branch or manually `touch .bookkeeper/metadata.yaml` on the target branch.
cc @jessesuen @christianh814 this tripped up both of you (and me too) at some point in recent weeks.

return error instead of panicking upon branch hijacking

---

docs/docs/30-how-to-guides/10-configuration.mdx

Found one left-over reference to `Bookkeeper.yaml` - this sadly cost me an hour tonight ;-)

doc: Fix Bookfile.yaml file name

---

docs/docs/30-how-to-guides/10-configuration.mdx
internal/helm/config.go
internal/helm/helm.go
rendering.go
rendering_test.go
schema.json
service.go

Introduces a new config option into `Bookfile.yaml` to set the helm namespace since some charts consume `.Release.Namespace` in their templates.
If string is empty, reposerver will not append the `--namespace` parameter.
With namespace set
```
INFO[0001] Trace   args="[helm template . --name-template podinfo --namespace podinfo --values /tmp/4176594743/repo/chart/values-dev.yaml --include-crds]" dir=/tmp/4176594743/repo/chart operation_name="exec helm" time_ms=82.134863
```
Without
```
INFO[0002] Trace   args="[helm template . --name-template podinfo --values /tmp/876360118/repo/chart/values-dev.yaml --include-crds]" dir=/tmp/876360118/repo/chart operation_name="exec helm" time_ms=168.38142200000001
```
```yaml
- pattern: env/(\w+)
appConfigs:
podinfo:
configManagement:
helm:
releaseName: …
```

Support setting helm namespace in Bookfile

---

.github/workflows/release.yaml

Existing permissions for publishing images to ghcr seems to have been broken by the recent repo and package rename.
Previously, we were managing a token with specific permissions stored as secret `GH_TOKEN`.
This PR just requests the necessary permissions for the default `GITHUB_TOKEN` that is automatically associated with every Actions workflow run.
I am also removing the explicit login step. I _think_ it's not needed anymore when doing things this way. If I'm wrong, I'll be putting that step back later.

adjust permissions on release process

---

CODEOWNERS

Swapping individuals with teams in CODEOWNERS to avoid spamming everyone with emails on each PR.
Also closes #199

chore: use teams instead of individuals in CODEOWNERS

---

cmd/cli/cli.go

@alexmt you might be the best person to review this.
This is a prereq for https://github.com/akuity/kargo/issues/951

suppress logging from repo server

---

branches.go
branches_test.go

Fixes #205
cc @evgeny-goldin @shelby-moore

clean commit branches more thoroughly

---

branches.go
branches_test.go
config.go
schema.json

Fixes #210 
cc @evgeny-goldin @shelby-moore as we discussed yesterday.

add config option to exempt specific paths from pre-render branch cleaning

---

docs/docs/30-how-to-guides/10-configuration.mdx
docs/docs/30-how-to-guides/30-docker-image.md

This has tripped me up with Argo CD since 2019 :)
Also, updating `docker run` example to reference latest rc.34 (which has backwards breaking changes).

docs: helm parameter is valueFiles, not valuesFiles

---

docs/docs/30-how-to-guides/20-github-actions.md

I briefly got confused by the name of the GitHub Action referenced in the docs.  I've submitted a similar PR to update the README in the 'kargo-render-action' project too (https://github.com/akuity/kargo-render-action/pull/3).  Also, updated version to latest latest rc.34.

docs: GitHub Action is kargo-render-action, not akuity-kargo-render

---

internal/argocd/render.go
rendering.go
service.go

When invoking the repo server, we've been passing (typically) a relative `path` (aka `appPath` in Argo CD code) and an empty `repoRoot`.
This has been adversely impacting our ability to resolve Helm values files under certain circumstances.
e.g.:
```
error pre-rendering manifests: error generating manifests using Argo CD repo server: error resolving helm value files: error resolving value file path: file 'env/dev/values.yaml' resolved to outside repository root
```
[This comment](https://github.com/argoproj/argo-cd/blob/master/util/io/path/resolved.go#L84-L111) from within Argo CD source code explains:
```golang
// ResolveValueFilePathOrUrl will inspect and resolve given file, and make sure that its final path is within the boundaries of
// the path specified in repoRoot.
//
// appPath is …
```

fix: do not pass relative path and empty repoRoot to repo server

---

docs/docs/30-how-to-guides/10-configuration.mdx

I think it's fair to say that not everyone's first language is English, and when that's the case, coming across words like `denizens` makes it difficult to understand an already complex topic. Frankly, it's a word I didn't know but could understand with context and definition. However, I think it would make the docs more accessible to use a more familiar (simpler?) word to get the same point across.
I won't die on this hill, but I wanted to open up the conversation!
> Yeah, this whole PR is a nit, but I like semantics :smile:

docs: use common language to keep content accessible

---

.github/workflows/ci.yaml
.golangci.yaml
Dockerfile
branches.go
cmd/action_cmd.go
cmd/action_cmd_test.go
cmd/flags.go
cmd/root_cmd.go
context.go
docs/docs/30-how-to-guides/30-docker-image.md
go.mod
go.sum
pkg/git/git.go
pkg/git/git_test.go
service.go
types.go
validation.go
validation_test.go

Fixes #229 and is a key enabler for https://github.com/akuity/kargo/issues/1330
Full context -- when I implement #1330, Kargo proper will begin treating Kargo Render more similarly to how it treats Kustomize and Helm. Kargo will coordinate clones, commits, PRs, etc. leaving _rendering only_ to Kargo Render.
New options:
* Kargo Render can be invoked with a path to an existing repo, which it will _copy_ to a temporary directory so that it can monkey around with it safely.
* Kargo Render can write output back to a remote repo (the default), a specified path (Kargo proper will use this option), or stdout (primarily for test/debugging purposes).
Kargo Render retains the ability to do its own clones, commits, etc., simply because the Kargo Render Action needs it.
Also, since I added some new, …

feat: add options for where input comes from and where output goes to

---

branches.go
docs/docs/30-how-to-guides/30-docker-image.md
pkg/git/git.go
service.go

As a safeguard, Kargo render has long refused to write rendered config to a branch that doesn't already appear to be managed via Kargo Render. The signal that a branch _is_ managed by Kargo Render has always been the existence of branch metadata in `.kargo-render/metadata.yaml`.
This means that when _creating_ new, orphaned, stage-specific branches, we have always written blank metadata to the new branch.
The trouble with this approach is that Kargo proper (rather than Kargo Render) will, at times, be responsible for creation of stage-specific branches -- and when doing so, it doesn't (and shouldn't) particularly care about writing Kargo Render metadata into that new branch.
This PR changes some internal Kargo Render logic so that if we check out an existing branch that doesn't already …

improve how new branches are created

---

branches.go
branches_test.go
config_test.go
docs/docs/30-how-to-guides/30-docker-image.md
pkg/git/git.go
rendering.go
service.go
service_test.go

When we write to a stage-specific branch, we gut its existing contents entirely and render into the empty directory. The long-time exception to that has been that we do _not_ delete any files or directories explicitly named in the Kargo Render config as `preservedPaths`.
Only if writing to a local directory instead of a remote branch, all files that were meant to be preserved are going missing. The reason is that we have been rendering into a _brand new, empty directory_, when really, we should have been _copying_ whatever was to be preserved from the target branch.
Note that since I worked on a new test case that involved a temporary directory, I have also taken the liberty of fixing a few outstanding temp directory-related nits.

fix: preserve files correctly when rendering to a local directory

---

.github/workflows/ci.yaml
.golangci.yaml
Dockerfile.dev

While dealing with some deprecations. For more details around those, see the comments made in https://github.com/akuity/kargo/pull/1811

chore(deps): bump golangci-lint to 1.57.2

---

Dockerfile

fixes issues like #222 where kustomize is trying to use flag `--repo` on `helm pull` for oci:// repositories

chore(deps): bump kustomize version on Docker image

---

Dockerfile

This gives us a much newer `git` binary.

upgrade alpine to 3.20.0

---

.github/dependabot.yml
.github/workflows/ci.yaml
.github/workflows/governance.yaml
.github/workflows/release.yaml

- Pin actions to SHAs.
- Set permissions on all workflows.
- Enable Dependabot for GitHub Actions.

chore: harden GitHub Actions workflows

---

.github/workflows/release.yaml

The [last attempted release](https://github.com/akuity/kargo-render/actions/runs/10271352103) of Kargo-Render failed, due it seems to the upgraded `cosign` binary that came in with #297.
This PR adjusts the image build and signing process to be more similar to that used by Kargo proper.
cc @34fathombelow

update image signing process

---

branches.go
cmd/kargo-render/output.go
config.go
go.mod
go.sum
internal/manifests/manifests.go
internal/manifests/manifests_test.go

This is an alternative approach to #305, to solve the issues described in #278 and #294 using a YAML reader that properly understands YAML document separators.

fix(manifests): split YAML using reader
